# Generated by Django 2.2.6 on 2020-05-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('lang', models.CharField(max_length=20, verbose_name='Lang')),
                ('word', models.CharField(max_length=20, verbose_name='Word')),
                ('p_o_s', models.CharField(blank=True, max_length=20, verbose_name='PoS')),
                ('level', models.CharField(blank=True, max_length=20, verbose_name='Level')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='Rank')),
            ],
        ),
    ]
