# Generated by Django 2.2.6 on 2020-05-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdpt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('listname', models.CharField(max_length=20, verbose_name='List Name')),
                ('word', models.CharField(max_length=20, verbose_name='Word')),
                ('p_o_s', models.CharField(blank=True, max_length=20, verbose_name='PoS')),
                ('level', models.CharField(blank=True, max_length=20, verbose_name='Level')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='Rank')),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('listname', models.CharField(max_length=20, verbose_name='List Name')),
                ('word', models.CharField(max_length=20, verbose_name='Word')),
                ('p_o_s', models.CharField(blank=True, max_length=20, verbose_name='PoS')),
                ('urank', models.PositiveIntegerField(default=0, verbose_name='URank')),
                ('phrase1', models.CharField(blank=True, max_length=50, verbose_name='Phrase1')),
                ('examples', models.CharField(blank=True, max_length=50, verbose_name='Examples')),
            ],
        ),
        migrations.DeleteModel(
            name='BasicWord',
        ),
    ]
